# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{addressable_record}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)"]
  s.date = %q{2010-09-21}
  s.description = %q{Encapsulates the composed of pattern for addresses into any easy to use library.  Provides convenience methods for formatting, parsing, etc.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "addressable_record.gemspec",
     "lib/addressable_record.rb",
     "lib/addressable_record/active_record_extesions.rb",
     "lib/addressable_record/address.rb",
     "lib/addressable_record/states.rb",
     "rails_generators/addressable_record_migration_generator/addressable_record_migration_generator.rb",
     "rails_generators/addressable_record_migration_generator/templates/migration.rb",
     "script/console",
     "script/environment.rb",
     "script/seed.rb",
     "spec/addressable_record/address_parsing_shared_spec.rb",
     "spec/addressable_record/address_spec.rb",
     "spec/addressable_record_spec.rb",
     "spec/database.yml",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/midas/addressable_record}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Encapsulates the composed of pattern for addresses into any easy to use library.}
  s.test_files = [
    "spec/addressable_record/address_parsing_shared_spec.rb",
     "spec/addressable_record/address_spec.rb",
     "spec/addressable_record_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<geographer>, [">= 1.1.1"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<geographer>, [">= 1.1.1"])
      s.add_dependency(%q<activerecord>, [">= 2.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<geographer>, [">= 1.1.1"])
    s.add_dependency(%q<activerecord>, [">= 2.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

